#!/bin/bash
DIR=`pwd | sed -e 's/.*\///'`
DRYDOCK=`pwd | grep drydock`
if [ "$DRYDOCK" == "" ]; then
  echo COMMITTING LIVE
else
  DIR=drydock_$DIR
fi
echo $DIR
echo Locking...
ssh root@$DIR "/root/lock `./ssh_config.py $DIR user`"
