#!/bin/bash
DIR=`pwd | sed -e 's/.*\///'`
DRYDOCK=`pwd | grep drydock`
if [ "$DRYDOCK" == "" ]; then
  echo COMMITTING LIVE
else
  DIR=drydock_$DIR
fi
echo $DIR
echo Unlocking...
ssh root@$DIR "/root/unlock `./ssh_config.py $DIR user`"
